export default {
  headerBackground: "#fa0150",
  buttonBorderColor: "#FC642D",
  buttonBackground: "white",
  buttonHover: "#f7f7f7",
  buttonBottom: "#ebebeb",
  inputBorder: "#ebebeb",
  inputPlaceholderColor: "#767676",
  inputFocused: "#ff385c",
  inputErrorMessage: "#ff5a5f",
  inputErrorBackground: "#fff8f6",
  selectorBackground: "white",
  selectorBorder: "#ebebeb",
  selectorFocused: "#ff385c",
  selectorInfo: "#484848",
};
