export default {
  headerBackground: "#fa0150",
  buttonBorderColor: "#FC642D",
  buttonBackground: "white",
  buttonHover: "#f7f7f7",
  buttonBottom: "#ebebeb",
  darkCyan: "#008489",
  divider: "#ddd",
  inputBorder: "#ebebeb",
  inputPlaceholderColor: "#767676",
  inputFocused: "#ff385c",
  inputErrorMessage: "#ff5a5f",
  inputErrorBackground: "#fff8f6",
  selectorBackground: "white",
  selectorBorder: "#ebebeb",
  selectorFocused: "#ff385c",
  selectorInfo: "#484848",
  selectorWarning: "#c13515",
  selectorWarningBackground: "#fff8f6",
  passwordWarning: "#c13515",
  passwordPass: "#008a05",
  usermenuBackground: "#f7f7f7",
};
